---
# handlers file for osmc
- name: restart nrpe
    service:
        name: nagios-nrpe-server
        state: restarted
    become: True
- name: restart sssd
    service:
        name: sssd
        state: restarted
    become: True
- name: restart kodi
    service:
        name: mediacenter
        state: restarted
    become: True

